CREATE TABLE PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    PRICE DECIMAL(10,2),
    BARCODE VARCHAR(255) UNIQUE KEY,
    ID_CATEGORY BIGINT
);

CREATE TABLE CATEGORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE KEY,
    DESCRIPTION VARCHAR(255),
    ACTIVE BOOLEAN
);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID);